version: "3.9"

services:
  pg:
    image: postgres:13.3-buster@sha256:b6df1345afa5990ea32866e5c331eefbf2e30a05f2a715c3a9691a6cb18fa253
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
    volumes:
      - pg:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.19-management@sha256:e311fdb577539ea7d767058d853a04d39694292993c03c06212155a143fb5e40
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "nienna"
      RABBITMQ_DEFAULT_PASS: "nienna123"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  pg:
  rabbitmq: