version: "3.9"

services:
  pg:
    image: postgres:13.3-buster@sha256:6647385dd9ae11aa2216bf55c54d126b0a85637b3cf4039ef24e3234113588e3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
    volumes:
      - pg:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.19-management@sha256:d29cecf88403af0a7bf3edad3a2980a205cef7c22c679e8aa1b13d4d6cc10d18
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "nienna"
      RABBITMQ_DEFAULT_PASS: "nienna123"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  pg:
  rabbitmq: