version: "3.9"

services:
  pg:
    image: postgres:13.4-buster@sha256:97e5e91582e89514277912d4b7c95bceabdede3482e32395bcb40099abd9c506
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
    volumes:
      - pg:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.9-management@sha256:03cbd910e2eb557dbabd39904f897fce3cb1bb7cea6c3045ddcf471b2f07ca10
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "nienna"
      RABBITMQ_DEFAULT_PASS: "nienna123"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  pg:
  rabbitmq: