version: "3.9"

services:
  cliff:
    build: cliff
    restart: unless-stopped
    # TMP
    ports:
      - "8000:8000"
    environment:
      DB_URI: "postgresql://db/nienna?user=nienna&password=nienna"
      # If NIENNA_DEV is defined, debug logs are printed
      NIENNA_DEV: "true"
    depends_on:
      - db

#  backburner:
#    build: backburner
#
#  traefik:
#    build: services/traefik
#
#  rabbitmq:
#    build: services/rabbitmq
#
  db:
    build: services/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
#
#  s3:
#    build: services/minio
#    ports:
#      - "9000:9000"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: minio123
#    command: server /home/shared
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3