version: "3.9"

services:
  db:
    build: services/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"

  redis:
    build: services/redis
    restart: unless-stopped

  #  rabbitmq:
  #    build: services/rabbitmq
  #
  #  s3:
  #    build: services/minio
  #    ports:
  #      - "9000:9000"
  #    environment:
  #      MINIO_ROOT_USER: minio
  #      MINIO_ROOT_PASSWORD: minio123
  #    command: server /home/shared
  #    healthcheck:
  #      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
  #      interval: 30s
  #      timeout: 20s
  #      retries: 3

  caddy:
    build: services/caddy
    ports:
      - "80:80"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile