version: "3.9"

services:
  pg:
    image: postgres:13.4-buster@sha256:97e5e91582e89514277912d4b7c95bceabdede3482e32395bcb40099abd9c506
    restart: unless-stopped
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-buster@sha256:11f7040a861a1456ecad6d58babe47e2c8d05b626187a671bd72aa876d7cd419
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.13-management@sha256:931b345ec78aff3b357bda335bad61b466ef11c3477d37c91e2ecbfab71483f7
    restart: unless-stopped
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "nienna"
      RABBITMQ_DEFAULT_PASS: "nienna123"

  s3:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z@sha256:552e1b5f97878dcd8aae0df1d0a8dcd15a935124bfcbc92041ec31c9b24c898d
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_ACCESS_KEY: "47cd7dd52abc74f798c6f36a3ff2f6df0637431418c8f5373b31ce7a19d98183" # YES TODO: remove
      MINIO_SECRET_KEY: "20282d88b1979a53ac09caba531d57065f026b0b2a7f68f81ed4294cb9df6300" # YES TODO: remove
    command: server /home/shared
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - s3:/home/shared

  loadbalancer:
    image: traefik:v2.6@sha256:e88f389b79b2c287650d11751e3375ece8c5e21bd77100a22e7d0ded2a457d6f
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - $PWD/.docker/loadbalancer/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webapp
      - cliff

volumes:
  pg:
  s3: