version: "3.9"

services:
  pg:
    image: postgres:13.3-buster@sha256:b6df1345afa5990ea32866e5c331eefbf2e30a05f2a715c3a9691a6cb18fa253
    restart: unless-stopped
    environment:
      POSTGRES_DB: "nienna"
      POSTGRES_USER: "nienna"
      POSTGRES_PASSWORD: "nienna"
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5-buster@sha256:fc18060a624d55a2f68428955505623471efa5ed0158f9c74f7414fdc0294740
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.19-management@sha256:e311fdb577539ea7d767058d853a04d39694292993c03c06212155a143fb5e40
    restart: unless-stopped
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "nienna"
      RABBITMQ_DEFAULT_PASS: "nienna123"

  s3:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z@sha256:a7b01f7ea0e788466c94dcee588b557377b9b260e51919b0e200daab4ab1777f
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_ACCESS_KEY: "47cd7dd52abc74f798c6f36a3ff2f6df0637431418c8f5373b31ce7a19d98183" # YES TODO: remove
      MINIO_SECRET_KEY: "20282d88b1979a53ac09caba531d57065f026b0b2a7f68f81ed4294cb9df6300" # YES TODO: remove
    command: server /home/shared
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - s3:/home/shared

  loadbalancer:
    image: nginx:1.21.1@sha256:3f13b4376446cf92b0cb9a5c46ba75d57c41f627c4edb8b635fa47386ea29e20
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/.docker/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg:
  s3: