version: "3.9"

services:
  cliff:
    build: ../cliff
    restart: unless-stopped
    environment:
      DB_URI: "postgresql://db/nienna?user=nienna&password=nienna"
      REDIS_URI: "redis:6379"
      S3_URI: "s3:9000"
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123" # Yes
      RABBITMQ_URI: "amqp://nienna:nienna123@rabbitmq:5672/"
      # If NIENNA_DEV is defined, debug logs are printed
      NIENNA_DEV: "true"
      SESSION_KEY: "95c5a0ae-6bd8-4866-81d3-6f67223f8ff2"
    depends_on:
      - db
      - redis
      - s3
      - rabbitmq

#  backburner:
#    build: backburner