version: "3.9"

services:
  cliff:
    build: ../cliff
    restart: unless-stopped
    environment:
      DB_URI: "postgresql://pg/nienna?user=nienna&password=nienna"
      REDIS_URI: "redis:6379"
      S3_URI: "s3:9000"
      S3_DISABLE_TLS: "true"
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123" # Yes
      AMQP_URI: "amqp://nienna:nienna123@rabbitmq:5672"
      # If NIENNA_DEV is defined, debug logs are printed
      NIENNA_DEV: "true"
      SESSION_KEY: "95c5a0ae-6bd8-4866-81d3-6f67223f8ff2"
      NIENNA_ADMIN_PASSWORD: "adminpassword"
    depends_on:
      - db
      - redis
      - s3
      - rabbitmq

  backburner:
    build: ../backburner
    restart: unless-stopped
    environment:
      RUST_LOG: "DEBUG"
      S3_URI: "http://s3:9000"
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123" # Yes
      AMQP_URI: "amqp://nienna:nienna123@rabbitmq:5672"
    depends_on:
      - s3
      - rabbitmq

  pulsar:
    build: ../pulsar
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      LOG_LEVEL: "debug"
      DB_URI: "Host=pg;Username=nienna;Password=nienna;Database=nienna"
      AMQP_URI: "amqp://nienna:nienna123@rabbitmq:5672"
    depends_on:
      - rabbitmq
      - db

  db:
    build: ../db
    restart: on-failure
    environment:
      DB_URI: "postgresql://pg/nienna?user=nienna&password=nienna"
      NIENNA_ADMIN_PASSWORD: "adminpassword"
    depends_on:
      - pg

  webapp:
    build: ../webapp
    restart: unless-stopped
    volumes:
      - $PWD/.docker/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - loadbalancer