global:
  sendAnonymousUsage: false

log:
  level: "INFO"
  format: "common"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    watch: true

api:
  dashboard: true
  insecure: true
