---
name: CI

on: [push]

jobs:
  Functional-Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_functional

  Dockerfile-Linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_dockerfiles

  Schema-Updated:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_schema

  Cliff-UnitTests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_cliff

  Db-UnitTests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_db

  Backburner-UnitTests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_backburner

  Pulsar-UnitTests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test_pulsar

  Webapp-Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd services/webapp && npm i && npm run build
